export {default as Loginbar} from './loginbar/Loginbar';
export {default as Navbar} from './navbar/Navbar';
export {default as Header} from "./header/Header"
export {default as Pcpa} from './pcpa/Pcpa';
export {default as Quotesection} from './quoteSection/Quotesection';
export {default as Works} from './works/Works';
export {default as Quotesection2} from './quoteSeection2/Quotesection2';
export {default as Pcpablog} from './pcpaBlog/Pcpablog';
export {default as Footer} from './footer/Footer';
